### ISSUE TITLE
Is the detector scale invariant ?

### ISSUE THREAD

**Issue by Amit12690** [KAIST-VCLAB/DeepFormableTag#1]
What is the resolution of the tags ?  Can the detector detect and decode even if the tags are resized to a larger resolution ?

**Comment by myaldiz** [comment]
Hi @Amit12690,

Q1: The model we provide generates 32x32 markers. 
Q2: Resizing is little tricky, it will work if you do it properly. Due to the nature of our rendering setup during training, I would suggest two methods:
1. Try to resize only to the multiples of 32x32 with the nearest neighbor sampling
2. First, try to resize a resolution with the nearest neighbor sampling, that is multiple of 32x32 and larger than intended resolution.  Then, apply bilinear sampling to generate intended resolution. 

The reason is we assume our markers (in this case 32x32) are drawn in vector graphics format (as 32x32 neighboring squares). When printed they are rasterized following their definition. This is what we try to simulate in our training setup which detector learns from.

I suggest you to check out the [code to generate markers in vector-graphics pdf format](https://github.com/KAIST-VCLAB/DeepFormableTag/tree/master/tools#generating-board-pdfs) so that you don't have to deal with the sampling artifacts while printing. You can [generate your own pdfs](https://github.com/KAIST-VCLAB/DeepFormableTag/tree/master/tools#marker-config-file) with custom placement setup that will work well with our detector.
