### ISSUE TITLE
Cannot find field 'gt_sample_locs' error 

### ISSUE THREAD

**Issue by Amit12690** [KAIST-VCLAB/DeepFormableTag#5]
I get the error :  AttributeError: Cannot find field 'gt_sample_locs' in the given Instances!  when trying model(inputs) in training mode.  It works fine during eval mode though.  

The dataset used :   test-realworld/deformation_10cm   since it has annotations.json

**Comment by myaldiz** [comment]
We generate `gt_sample_locs` and some other parameters during `dataset_mapper` part of the training code which is not included in the release yet. You will get several errors like that if you try to run the model in training mode since those are required for the loss calculation. I will make sure providing those parameters will be optional in the training release.
